### ISSUE TITLE
[error] Crashes, and i can't figure out why 

### ISSUE THREAD

**Issue by Sraleik** [cdrx/rancher-gitlab-deploy#16]
Hi, 
I'm currently having a lot of fun with docker, gitlab-ci and rancher :)
and was really happy to see your tool rancher-gitlab-deploy to deploy my build from gitlab to rancher
but unfortunately, i can't make it work.

I've try from gitlab-ci in a deploy job and on my local machine inside your docker.
I end up with the same pb. I'm not fluent in python so i don't understand much ^^

here is my stacktrace:

```sh 
upgrade --rancher-url http://MY_URL --rancher-key 4242424242 --rancher-secret blablablabala --environment production --stack MY_STACK --service apache --new-image MY_IMAGE --no-finish-upgrade

Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.2', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.2-py2.7.egg/rancher_gitlab_deploy/cli.py", line 57, in main
    environments = r.json()['data']
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR: Job failed: exit code 1
```

**Comment by cdrx** [comment]
What are you supplying for rancher-url? It should be just `http://rancher.yourcompany.com` or similar. 

Is Rancher behind a proxy or something? Does the Rancher web UI work correctly?

**Comment by Sraleik** [comment]
It works !! 
I was giving a redirected url in --rancher-url
With the direct url to my rancher it works perfectly :)

Thanks for your tool, and for your help

**Comment by cdrx** [comment]
No problem
