### ISSUE TITLE
random fail on service upgrade

### ISSUE THREAD

**Issue by madbean** [cdrx/rancher-gitlab-deploy#20]
Hello,

Thank you dude nice job with this tool !
Just to tell you sometime y have this error and i don t know why.. 

`$ upgrade --stack jankenpon --service jankenpon --no-start-before-stopping --environment lab

Upgrading JanKenPon/jankenpon in environment Lab...
Upgrade started, waiting for upgrade to complete...
Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.2', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.2-py2.7.egg/rancher_gitlab_deploy/cli.py", line 200, in main
    api, environment_id, service['id']
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))`

if i retry it s works

thank again.

`$ upgrade --stack jankenpon --service jankenpon --no-start-before-stopping --environment lab
Upgrading JanKenPon/jankenpon in environment Lab...
Upgrade started, waiting for upgrade to complete...
Finishing upgrade...
Upgrade finished

Build succeeded`

rancher ui is on and the url is http://someurl.domaine.ovh:8080

**Comment by cdrx** [comment]
Is there any sort of proxy or load balancer in front of your Rancher install? It looks like the request response gets broken somehow.

**Comment by madbean** [comment]
Hello 
Yes it s ok now, without load balancer 
Thank you so !!!
