### ISSUE TITLE
Error in error handling

### ISSUE THREAD

**Issue by boskiv** [cdrx/rancher-gitlab-deploy#26]
```
$ upgrade --environment Default --stack services --service bonus --no-finish-upgrade
Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.2', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.2-py2.7.egg/rancher_gitlab_deploy/cli.py", line 93, in main
    bail("Unable to find a stack called '%s'. Does it exist in the '%s' environment?" % environment_name)
TypeError: not enough arguments for format string
ERROR: Job failed: exit code 1
```

**Comment by cdrx** [comment]
Damn, errors in the errors. I'll fix that :) thanks for reporting.

**Comment by cdrx** [comment]
Now fixed, thanks again for reporting @boskiv
