### ISSUE TITLE
Add --new-sidekick-image

### ISSUE THREAD

**Issue by ghost** [cdrx/rancher-gitlab-deploy#9]
In Rancher you can specify multiple sidekicks. You add the "--sidekicks" option, which only makes pull a image from old path.
Which is needed that we can specify new image url for each sidekicks.

**Comment by czende** [comment]
+1

**Comment by cdrx** [comment]
This has been added in 1.3, thanks to a PR from @kariae 

```
rancher-gitlab-deploy --new-sidekick-image sidekick1 registry.fakename.com:5000/code:v0.0.2 --new-sidekick-image sidekick2 registry.fakename.com:5000/assets:v0.0.2
```

**Comment by khusseini** [comment]
@cdrx,
Somehow the update is not working for me with  a sidekick.
I got a sidekick for my `web` service which is called `app`

I tried the following:
```
docker run [...] cdrx/rancher-gitlab-deploy \
   upgrade \
   --environment=Default \
   --stack=php-app \
   --service web \
   --new-sidekick-image app registry.gitlab.com/myregistry/php-fpm-application:updated
```

I am getting an error 
```
Upgrading orocommerce-haneu/web in environment diePartments...
Traceback (most recent call last):
  File "/usr/local/bin/upgrade", line 11, in <module>
    load_entry_point('rancher-gitlab-deploy==1.4', 'console_scripts', 'rancher-gitlab-deploy')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rancher_gitlab_deploy-1.4-py2.7.egg/rancher_gitlab_deploy/cli.py", line 186, in main
    upgrade['inServiceStrategy']['secondaryLaunchConfigs'][idx]['imageUuid'] = 'docker:%s' % new_sidekick_image[secondaryLaunchConfigs['name']]
IndexError: list index out of range
```

When I run the update on the `web` service alone, it works out fine.
What am I doing wrong?

**Comment by khusseini** [comment]
@cdrx , I think I found the culprit. The `--sidekicks` parameter is required for this to work because in this line
https://github.com/cdrx/rancher-gitlab-deploy/blob/master/rancher_gitlab_deploy/cli.py#L186
the `upgrade['inServiceStrategy']['secondaryLaunchConfigs']` is not set if `--sidekicks` was not set.
